version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "hello world, from some_other_branch!"
  build-master:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "build-master echo"
  fail:
    docker:
      - image: alpine:latest
    steps:
      - run: exit 1
workflows:
  version: 2
  build-master:
    jobs:
      - build-master:
          filters:
            branches:
              only: master
  another-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: some_other_branch
      - fail
